/* Replace with your SQL commands */
CREATE TABLE PRODUCTS
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50),
    price    INTEGER,
    category VARCHAR(20)
);

CREATE TABLE USERS
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(50) UNIQUE,
    firstname VARCHAR(20),
    lastname  VARCHAR(50),
    password  VARCHAR
);

CREATE TABLE ORDERS
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER,
    quantity   INTEGER,
    user_id    INTEGER,
    status     VARCHAR(10),
    CONSTRAINT FK_ORDERS_PRODUCT FOREIGN KEY (product_id) REFERENCES PRODUCTS (id) ON DELETE CASCADE,
    CONSTRAINT FK_ORDERS_USERs FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

TRUNCATE PRODUCTS RESTART IDENTITY CASCADE;
TRUNCATE USERS RESTART IDENTITY CASCADE;
TRUNCATE ORDERS RESTART IDENTITY;
INSERT INTO PRODUCTS(name, price, category)
VALUES ('Bridge to Terabithia', 250, 'Book');
INSERT INTO USERS (username, firstname, lastname, password)
VALUES ('revir216', 'Nugyen', 'Mihn Cud', 'check');
INSERT INTO ORDERS (product_id, quantity, user_id, status)
VALUES (1, 1, 1, 'done');
--
-- #### User
-- - id
-- - firstName
-- - lastName
-- - password
--
-- #### Orders
-- - id
-- - id of each product in the order
-- - quantity of each product in the order
-- - user_id
-- - status of order (active or complete)